apiVersion: v1
kind: Secret
metadata:
  name: shipments-api-secret
  labels:
    app: shipments-api
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:Zuzuna!12@routebox-dev-db.ci9eo6i0ke27.us-east-1.rds.amazonaws.com:5432/postgres"


  API_KEY: "your-api-key"
