apiVersion: v1
kind: Service
metadata:
  name: shipments-api
  labels:
    app: shipments-api
spec:
  type: LoadBalancer
  selector:
    app: shipments-api
  ports:
    - port: 80
      targetPort: 3000
